# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = ["blowfish", "hugo-cite", "hugo-embed-pdf-shortcode"]
baseURL = "https://yangyangli.top/"
jefaultContentLanguage = "en"
enableInlineShortcodes = true

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 15
summaryLength = 0

buildDrafts = false
buildFuture = false

googleAnalytics = "G-9HEHRPMBLZ"

[imaging]
anchor = 'Center'

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = 'daily'
filename = 'sitemap.xml'
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]

[related]
threshold = 0
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name = "series"
weight = 50

[[related.indices]]
name = "authors"
weight = 20

[[related.indices]]
name = "date"
weight = 10

[[related.indices]]
applyFilter = true
name = 'fragmentrefs'
type = 'fragments'
weight = 10

[params]
opengraph_io_api_key = "f255fea7-4264-4c54-beeb-afc7978d7bd6"
